apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-rssagg.fullname" . }}-go-rssagg
  labels:
    app: go-rssagg
  {{- include "go-rssagg.labels" . | nindent 4 }}
spec:
  type: {{ .Values.goRssagg.type }}
  selector:
    app: go-rssagg
    {{- include "go-rssagg.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.goRssagg.ports | toYaml | nindent 2 }}
