name: Build and Push Docker Image

on:
  push:
    branches:
      - dev
      - prod

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository with full history to access tags
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to GHCR
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract branch and version
      - name: Set image tag
        id: tag
        run: |
          BRANCH=${{ github.ref_name }}
          # Get the tag for the current commit, strip 'v' prefix, or default to 'latest'
          VERSION=$(git tag --points-at HEAD | sed 's/^v//' | head -n 1)
          VERSION=${VERSION:-latest}
          echo "Branch: $BRANCH"
          echo "Version: $VERSION"
          echo "image_name=go-rssagg-$BRANCH" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      # Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/go-rssagg-${{ github.ref_name }}:${{ steps.tag.outputs.version }}
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.version=${{ steps.tag.outputs.version }}
            org.opencontainers.image.revision=${{ github.sha }}